FROM nginx:latest

COPY . /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# CMD ["nginx", "-g", "daemon off;"]
# CMD ["'/bin/sh -c'" , "while :;", "do sleep 6h & wait $%{!} nginx -s reload;" ]

EXPOSE 80 443